### ISSUE TITLE
Documentation is pretty scarce

### ISSUE THREAD

**Issue by Jakersnell** [vanruesc/esbuild-plugin-glsl#10]
I feel like this project could use a bit more documentation, even the `Usage` section is unclear. Could we please get more explicit documentation and examples.

**Comment by vanruesc** [comment]
Hey, sorry for the late response.

I think esbuild's [docs](https://esbuild.github.io/content-types/#text) regarding file imports sufficiently describe how this plugins works, but I'm ok with adding a simple example use case to the readme. PRs are welcome.
