### ISSUE TITLE
.wgsl file extension not supported

### ISSUE THREAD

**Issue by zentyk** [vanruesc/esbuild-plugin-glsl#2]
Files with .wgsl extension cannot be loaded when building a WebGPU project with .wgsl shaders. Those must be supported to allow users to use the plugin using WebGPU.

This change has been hardcoded in production and it works.

![image](https://user-images.githubusercontent.com/8301647/159802389-73c8a39f-afc7-4ecc-be27-2fa766e10863.png)

**Comment by vanruesc** [comment]
Looks good, would you like to make a PR?

**Comment by vanruesc** [comment]
Closed via #3.
