### ISSUE TITLE
Minify is breaking wgsl file

### ISSUE THREAD

**Issue by DeusProx** [vanruesc/esbuild-plugin-glsl#5]
When activating minifyfaction for wgsl files they are actually breaking, because of missing white spaces. This seems to be due to the new wgsl syntax with `@vertex` and `@fragment` instead of `[[stage(vertex)]]` and `[[stage(fragment)]]`. E.g. my shader function looks like

```
@vertex
fn vert_main(@builtin(vertex_index) VertexIndex : u32) -> VertexOutput {
  ....
}
```

This will get minified to

`@vertexfn vert_main(@builtin(vertex_index)VertexIndex:u32)->VertexOutput{...}`, but it should be 
`@vertex fn vert_main(@builtin(vertex_index)VertexIndex:u32)->VertexOutput{` so the browser can actually interpret it.

**Comment by vanruesc** [comment]
Fixed in `esbuild-plugin-glsl@1.1.1`.
